t_cell_data_columns = [('Reference', 'Assay IRI'),
                       ('Reference', 'Reference IRI'),
                       ('Epitope', 'Epitope IRI'),
                       ('Epitope', 'Description'),
                       ('Epitope', 'Antigen Name'),
                       ('Epitope', 'Parent Protein'),
                       ('Epitope', 'Parent Protein IRI'),
                       ('Epitope', 'Parent Species'),
                       ('Epitope', 'Parent Species IRI'),
                       ('Related Object', 'Epitope Relationship'),
                       ('Related Object', 'Description'),
                       ('Related Object', 'Parent Protein'),
                       ('Related Object', 'Parent Protein IRI'),
                       ('Related Object', 'Parent Organism'),
                       ('Related Object', 'Parent Organism IRI'),
                       ('Host', 'Host IRI'),
                       ('1st in vivo Process', 'Process Type'),
                       ('1st in vivo Process', 'Disease State'),
                       ('1st in vivo Process', 'Disease IRI'),
                       ('2nd in vivo Process', 'Process Type'),
                       ('2nd in vivo Process', 'Disease State'),
                       ('2nd in vivo Process', 'Disease IRI'),
                       ('Assay', 'Method/Technique'),
                       ('Assay', 'Assay Group'),
                       ('Assay', 'Qualitative Measure'),
                       ('Effector Cells', 'Cell Type'),
                       ('MHC', 'Allele Name')]

t_cell_columns = ['Assay ID', 'Reference ID', 'Epitope ID', 'Epitope', 'Antigen Name',
                  'Parent Protein', 'Parent Protein ID', 'Parent Species', 'Parent Species ID',
                  'Related Object Epitope Relationship', 'Related Object Epitope',
                  'Related Object Parent Protein', 'Related Object Parent Protein ID',
                  'Related Object Parent Organism', 'Related Object Parent Organism ID',
                  'Host ID', '1st in vivo Process Type', '1st in vivo Disease State',
                  '1st in vivo Disease ID', '2nd in vivo Process Type',
                  '2nd in vivo Disease State', '2nd in vivo Disease ID', 'Assay Method',
                  'Assay Group', 'Assay Qualitative Measure', 'Cell Type', 'MHC Allele Name']

b_cell_data_columns = [('Reference', 'Assay IRI'),
                       ('Reference', 'Reference IRI'),
                       ('Epitope', 'Epitope IRI'),
                       ('Epitope', 'Description'),
                       ('Epitope', 'Antigen Name'),
                       ('Epitope', 'Parent Protein'),
                       ('Epitope', 'Parent Protein IRI'),
                       ('Epitope', 'Parent Species'),
                       ('Epitope', 'Parent Species IRI'),
                       ('Related Object', 'Epitope Relationship'),
                       ('Related Object', 'Description'),
                       ('Related Object', 'Parent Protein'),
                       ('Related Object', 'Parent Protein IRI'),
                       ('Related Object', 'Parent Organism'),
                       ('Related Object', 'Parent Organism IRI'),
                       ('Host', 'Host IRI'),
                       ('1st in vivo Process', 'Process Type'),
                       ('1st in vivo Process', 'Disease State'),
                       ('1st in vivo Process', 'Disease IRI'),
                       ('2nd in vivo Process', 'Process Type'),
                       ('2nd in vivo Process', 'Disease State'),
                       ('2nd in vivo Process', 'Disease IRI'),
                       ('Assay', 'Method/Technique'),
                       ('Assay', 'Assay Group'),
                       ('Assay', 'Qualitative Measure'),
                       ('Antibody', 'Heavy Chain Type')]

b_cell_columns = ['Assay ID', 'Reference ID', 'Epitope ID', 'Epitope', 'Antigen Name',
                  'Parent Protein', 'Parent Protein ID', 'Parent Species', 'Parent Species ID',
                  'Related Object Epitope Relationship', 'Related Object Epitope',
                  'Related Object Parent Protein', 'Related Object Parent Protein ID',
                  'Related Object Parent Organism', 'Related Object Parent Organism ID',
                  'Host ID', '1st in vivo Process Type', '1st in vivo Disease State',
                  '1st in vivo Disease ID', '2nd in vivo Process Type',
                  '2nd in vivo Disease State', '2nd in vivo Disease ID', 'Assay Method',
                  'Assay Group', 'Assay Qualitative Measure', 'Heavy Chain Type']
